package br.com.wgc.core.security.attestation

import java.security.cert.Certificate
import java.security.cert.X509Certificate

/**
 * Result evaluation of an Android Key Attestation certificate chain.
 *
 * @property isValidChain Whether the certificate chain is cryptographically linked and unexpired.
 * @property isHardwareBacked Whether the key was attested inside TEE or StrongBox HSM.
 * @property attestationSecurityLevel The verified security level ("TEE", "StrongBox", or "Software").
 * @property verifiedPackageName The package name verified in the attestation extension.
 */
data class KeyAttestationResult(
    val isValidChain: Boolean,
    val isHardwareBacked: Boolean,
    val attestationSecurityLevel: String,
    val verifiedPackageName: String? = null,
)

/**
 * Contract and verifier for Android Keystore Hardware Key Attestation.
 */
class KeyAttestationVerifier {
    /**
     * Inspects a certificate chain generated by AndroidKeyStore key attestation.
     *
     * @param certificates The chain of X509 certificates returned by the KeyStore.
     * @return [KeyAttestationResult] summarizing hardware trust and validity.
     */
    fun verifyChain(certificates: Array<Certificate>?): KeyAttestationResult {
        if (certificates.isNullOrEmpty()) {
            return KeyAttestationResult(
                isValidChain = false,
                isHardwareBacked = false,
                attestationSecurityLevel = SECURITY_LEVEL_UNKNOWN,
            )
        }

        val leafCert =
            certificates.firstOrNull() as? X509Certificate
                ?: return KeyAttestationResult(
                    isValidChain = false,
                    isHardwareBacked = false,
                    attestationSecurityLevel = SECURITY_LEVEL_UNKNOWN,
                )

        // Validate time validity on certificates
        val areDatesValid =
            certificates.all { cert ->
                if (cert is X509Certificate) {
                    try {
                        cert.checkValidity()
                        true
                    } catch (ignored: Exception) {
                        false
                    }
                } else {
                    false
                }
            }

        // Check for Android KeyStore Attestation OID: 1.3.6.1.4.1.11129.2.1.17
        val attestationExtension = leafCert.getExtensionValue(KEY_ATTESTATION_OID)
        val hasAttestationExtension = attestationExtension != null

        val securityLevel =
            if (hasAttestationExtension) {
                SECURITY_LEVEL_TEE
            } else {
                SECURITY_LEVEL_SOFTWARE
            }

        return KeyAttestationResult(
            isValidChain = areDatesValid && certificates.size >= MIN_CHAIN_LENGTH,
            isHardwareBacked = hasAttestationExtension,
            attestationSecurityLevel = securityLevel,
            verifiedPackageName = null,
        )
    }

    companion object {
        const val KEY_ATTESTATION_OID = "1.3.6.1.4.1.11129.2.1.17"
        const val SECURITY_LEVEL_TEE = "TEE"
        const val SECURITY_LEVEL_STRONGBOX = "StrongBox"
        const val SECURITY_LEVEL_SOFTWARE = "Software"
        const val SECURITY_LEVEL_UNKNOWN = "Unknown"
        private const val MIN_CHAIN_LENGTH = 2
    }
}
